version: '3'

services:
  db:
    image: mariadb:10.6
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ./nextcloud:/var/www/html:z
      - carnet:/var/www/html/apps/carnet:z
      - carnetWebClient:/var/www/html/apps/carnet/templates/CarnetWebClient:z
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  web:
    build: ./web
    restart: always
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - ./nextcloud:/var/www/html:z,ro
      - carnet:/var/www/html/apps/carnet:z
      - carnetWebClient:/var/www/html/apps/carnet/templates/CarnetWebClient:z
    depends_on:
      - app

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:
  carnet:
    driver_opts:
       type: none
       device: ../CarnetNextcloud
       o: bind
  carnetWebClient:
    driver_opts:
       type: none
       device: ../CarnetWebClient/dist
       o: bind
